name = "tg-bot-downloader"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
BOT_TOKENS = ""
AUTO_DELETE_SECONDS = "300"
ASSEMBLYAI_API_KEY = ""

[[r2_buckets]]
binding = "VIDEOS"
bucket_name = "tg-bot-videos"

[[kv_namespaces]]
binding = "CACHE"
id = ""

[[d1_databases]]
binding = "DB"
database_name = "tg-bot-db"
database_id = ""
